[project]
name = "streamlit-01"
version = "0.1.0"
description = "SQL Streamlit"
readme = "README.md"
authors = [
    { name = "roger437linux", email = "roger437linux@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.6",
    "pyodbc>=5.3.0",
    "sqlalchemy>=2.1.2",
    "streamlit>=1.64.0",
]

[project.scripts]
streamlit-01 = "streamlit_01:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
